apiVersion: nais.io/v1alpha1
kind: Application

metadata:
  labels:
    team: tsm
  name: tsm-database
  namespace: tsm
spec:
  image: {{image}}
  port: 8080
  replicas:
    max: 1
    min: 1
  resources:
    requests:
      cpu: 50m
      memory: 256Mi

