apiVersion: nais.io/v1alpha1
kind: Application

metadata:
  labels:
    team: tsm
  name: tsm-database
  namespace: tsm
spec:
  gcp:
    sqlInstances:
      - type: POSTGRES_14
        databases:
          - name: tsm-database-dev
            users:
              - name: tsm-database-extra-user
        diskAutoresize: true
        insights:
          enabled: true
        flags:
          - name: cloudsql.logical_decoding
            value: "on"
  image: {{image}}
  port: 8080
  replicas:
    max: 1
    min: 1
  resources:
    requests:
      cpu: 50m
      memory: 256Mi

